# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Java CI with Maven

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  tests:
    runs-on: ubuntu-latest
    name: UI Automation
    steps:
      - uses: actions/checkout@v2
      - name: Setup Java 8
        uses: actions/setup-java@v1
        with:
          java-version: 8
      - name: Setup Zalenium Server
        uses: ajinx/zalenium@1.1
      - name: Setup Appium Server
        uses: moatazeldebsy/Appium-Server-GitHub-Action@V1.0.5
      - name: Prepare iPhone SE (2nd generation) simulator
        uses: futureware-tech/simulator-action@v1
        with:
          model: 'iPhone SE (2nd generation)'
          os_version: 14.4
      - name: Prepare android emulator
        uses: reactivecircus/android-emulator-runner@v2
        env:
          SELENIUM_HUB_HOST: 'localhost'
        with:
          arch: x86_64
          api-level: 29
          profile: pixel_3
          script: mvn -B clean test -Dcloud=localhost -Denvironment=qa -Dheadless=true --file pom.xml
      - name: Get Allure history
        uses: actions/checkout@v2
        if: always()
        continue-on-error: true
        with:
          ref: gh-pages
          path: gh-pages
      - name: Create allure report
        uses: simple-elf/allure-report-action@master
        if: always()
        id: allure-report
        with:
          allure_results: ./target/allure-results
          allure_report: allure-report
          allure_history: allure-history
      - name: Deploy report to Github Pages
        if: always()
        uses: peaceiris/actions-gh-pages@v2
        env:
          PERSONAL_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PUBLISH_BRANCH: gh-pages
          PUBLISH_DIR: allure-history